version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ~/.ssh:/root/.ssh
      - bundle_cache:/bundle
      - .:/app
    ports:
      - "3000:3000"

volumes:
  bundle_cache: {}